# _config.yml

# Outras configurações...

title: "Projeto de Chatbot com Modelos GPT-2 🤖"
description: >
  Bem-vindo ao nosso projeto de chatbot, impulsionado pela potência dos modelos GPT-2!
  Nossa missão é proporcionar uma experiência interativa e envolvente por meio de
  conversas naturalmente geradas. Junte-se a nós para explorar diálogos cativantes
  e contribua para a evolução deste inteligente chatbot. 🚀

# Outras configurações...

